name: Deploy to scseoexperts.com (SFTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Secure SFTP deploy with SSH key
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./"
          remote_path: ${{ secrets.REMOTE_PATH }}/
          sftp_only: true
          dry_run: true          # first run = simulate only
          exclude: |
            **/.git*
            **/.github/**/*
            **/.vscode/**/*
            **/node_modules/**/*
            **/dist/**/*
            **/*.log
            **/*.zip
